MotoSellProjekt/MotoSell/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rejestracja', views.rejestracja, name='rejestracja'),
    path('login', views.login, name='login'),
    path('wyloguj', views.wyloguj, name='wyloguj'),
    path('pojazdy/kreator', views.kreator, name='kreator'),
    path('pojazdy', views.pojazdy, name='pojazdy'),
    path('pojazdy/moje/', views.moje_pojazdy, name='moje_pojazdy'),
    path('pojazdy/<int:pk>', views.oferta, name='oferta'),
    path('pojazdy/<int:pk>/publikuj', views.publikuj, name='publikuj'),
    path('pojazdy/<int:pk>/cofnij_publikacje', views.cofnij_publikacje, name='cofnij_publikacje'),
    path('pojazdy/<int:pk>/usun', views.usun, name='usun'),
    path('pojazdy/<int:pk>/edytuj', views.edytuj, name='edytuj'),
]

MotoSellProjekt/MotoSellProjekt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import MotoSellProjekt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MotoSell.urls')),
    path('api/', include('MotoSell.urls_api'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MotoSellProjekt/MotoSell/models.py
from django.db import models
from django.contrib.auth.models import User

class Pojazd(models.Model):
    KATEGORIE = {
        "motocykl": "Motocykl",
        "osobowy": "Osobowy",
        "ciezarowy": "Ciężarowy"
    }
    PALIWO = {
        "benzyna": "Benzyna",
        "diesel": "Diesel",
        "lpg": "LPG"
    }

    tytul = models.CharField(max_length=100)
    opis = models.TextField()
    kategoria = models.CharField(max_length=10, choices=KATEGORIE.items())
    marka = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    rok_produkcji = models.PositiveIntegerField()
    przebieg = models.PositiveIntegerField()
    pojemnosc_skokowa = models.PositiveIntegerField()
    rodzaj_paliwa = models.CharField(max_length=10, choices=PALIWO.items())
    uzytkownik = models.ForeignKey(User, on_delete=models.CASCADE)
    data_dodania = models.DateField(auto_now_add=True)
    data_publikacji = models.DateField(null=True, blank=True)
    czy_opublikowany = models.BooleanField(default=False)
    czy_usuniety = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.pk}. {self.uzytkownik.username} {self.marka} {self.model}"

class Zdjecie(models.Model):
    zdjecie = models.ImageField(upload_to="zdjecia")
    pojazd = models.ForeignKey(Pojazd, on_delete=models.CASCADE)
    czy_glowny = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.zdjecie}"

MotoSellProjekt/MotoSell/forms.py
from django.forms import ModelForm, inlineformset_factory
from .models import Pojazd, Zdjecie

class PojazdForm(ModelForm):
    class Meta:
        model = Pojazd
        exclude = ['uzytkownik', 'data_dodania', 'data_publikacji', 'czy_usuniety']
        labels = {
            'czy_opublikowany': "Czy chcesz opublikować ofertę?"
        }

class ZdjecieForm(ModelForm):
    class Meta:
        model = Zdjecie
        fields = ['zdjecie']

ZdjecieFormSet = inlineformset_factory(Pojazd, Zdjecie, ZdjecieForm, can_delete=False, extra=5, max_num=5, min_num=1)

MotoSellProjekt/MotoSell/views.py
from django.contrib.auth import logout, login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .forms import PojazdForm, ZdjecieFormSet
from .models import Pojazd, Zdjecie
import datetime

def index(request):
    return redirect("pojazdy")

def rejestracja(request):
    if request.method == "POST":
        formularz_rejestracji = UserCreationForm(request.POST)
        if formularz_rejestracji.is_valid():
            nowy_uzytkownik = formularz_rejestracji.save()
            auth_login(request, nowy_uzytkownik)
            return redirect("pojazdy")
    else:
        formularz_rejestracji = UserCreationForm()

    return render(request, "MotoSell/rejestracja.html", {
        "formularz_rejestracji": formularz_rejestracji
    })

def login(request):
    if request.method == "POST":
        formularz_logowania = AuthenticationForm(data=request.POST)
        if formularz_logowania.is_valid():
            nowy_uzytkownik = formularz_logowania.get_user()
            auth_login(request, nowy_uzytkownik)
            return redirect("pojazdy")
    else:
        formularz_logowania = AuthenticationForm()

    return render(request, "MotoSell/login.html", {
        "formularz_logowania": formularz_logowania
    })


@login_required
def wyloguj(request):
    logout(request)
    return redirect("pojazdy")

@login_required
def kreator(request):
    if request.method == "POST":
        formularz_pojazdu = PojazdForm(request.POST, request.FILES)
        formset_galerii = ZdjecieFormSet(request.POST, request.FILES)
        if formularz_pojazdu.is_valid() and formset_galerii.is_valid():
            pojazd = formularz_pojazdu.save(commit=False)
            pojazd.uzytkownik = request.user
            if pojazd.czy_opublikowany:
                pojazd.data_publikacji = datetime.date.today()
            pojazd.save()
            formset_galerii.instance = pojazd
            formset_galerii.save()
            pierwsze_zdjecie = Zdjecie.objects.filter(pojazd=pojazd).first()
            if pierwsze_zdjecie:
                pierwsze_zdjecie.czy_glowny = True
                pierwsze_zdjecie.save()
            return redirect("/pojazdy")
    else:
        formularz_pojazdu = PojazdForm()
        formset_galerii = ZdjecieFormSet(instance=Pojazd())
    return render(request, "MotoSell/kreator.html", {
        "formularz_pojazdu": formularz_pojazdu,
        "formset_galerii": formset_galerii
    })

def pojazdy(request):
    pojazdy_wszystkie = Pojazd.objects.filter()
    return render(request, "MotoSell/pojazdy.html", {
        "pojazdy_wszystkie": pojazdy_wszystkie
    })

@login_required
def moje_pojazdy(request):
    pojazdy_wszystkie = Pojazd.objects.filter()
    return render(request, "MotoSell/moje_pojazdy.html", {
        "pojazdy_wszystkie": pojazdy_wszystkie
    })

def oferta(request, pk):
    if request.user.is_authenticated:
        pojazd = get_object_or_404(Pojazd, Q(pk=pk) & Q(czy_usuniety=False) & (Q(czy_opublikowany=True) | Q(uzytkownik=request.user)))
    else:
        pojazd = get_object_or_404(Pojazd, pk=pk, czy_opublikowany=True, czy_usuniety=False)
    return render(request, "MotoSell/oferta.html",{
        "pojazd": pojazd
    })

@login_required
def publikuj(request, pk):
    pojazd = get_object_or_404(Pojazd, pk=pk, uzytkownik=request.user)
    pojazd.czy_opublikowany = True
    pojazd.data_publikacji = datetime.datetime.now()
    pojazd.save()
    return redirect("oferta", pk=pk)

@login_required
def cofnij_publikacje(request, pk):
    pojazd = get_object_or_404(Pojazd, pk=pk, uzytkownik=request.user)
    pojazd.czy_opublikowany = False
    pojazd.data_publikacji = None
    pojazd.save()
    return redirect("oferta", pk=pk)

@login_required
def usun(request, pk):
    pojazd = get_object_or_404(Pojazd, pk=pk, uzytkownik=request.user)
    pojazd.czy_usuniety = True
    pojazd.save()
    return redirect("moje_pojazdy")

@login_required
def edytuj(request, pk):
    pojazd = get_object_or_404(Pojazd, pk=pk, uzytkownik=request.user)
    if request.method == "POST":
        formularz_pojazdu = PojazdForm(request.POST, request.FILES, instance=pojazd)
        formset_galerii = ZdjecieFormSet(request.POST, request.FILES, instance=pojazd)
        if formularz_pojazdu.is_valid() and formset_galerii.is_valid():
            zmodyfikowany_pojazd = formularz_pojazdu.save(commit=False)
            zmodyfikowany_pojazd.uzytkownik = request.user
            if zmodyfikowany_pojazd.czy_opublikowany and not zmodyfikowany_pojazd.data_publikacji:
                zmodyfikowany_pojazd.data_publikacji = datetime.date.today()
            zmodyfikowany_pojazd.save()
            formset_galerii.save()
            pierwsze_zdjecie = Zdjecie.objects.filter(pojazd=pojazd).first()
            if pierwsze_zdjecie:
                Zdjecie.objects.filter(pojazd=pojazd, czy_glowny=True).update(czy_glowny=False)
                pierwsze_zdjecie.czy_glowny = True
                pierwsze_zdjecie.save()
            return redirect("oferta", pk=pk)
    else:
        formularz_pojazdu = PojazdForm(instance=pojazd)
        formset_galerii = ZdjecieFormSet(instance=pojazd)
    return render(request, "MotoSell/edytuj.html", {
        "formularz_pojazdu": formularz_pojazdu,
        "formset_galerii": formset_galerii
    })

MotoSellProjekt/MotoSell/templates/MotoSell/base.html
<!DOCTYPE html>
<html lang="pl">
{% load static %}
    <head>
        <meta charset="UTF-8">
        <title>MotoSell</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <div class="nav">
            {% if request.user.is_authenticated %}
                <ul>
                    <li><a href="{% url 'pojazdy' %}">MotoSell</a></li>
                    <li><a href="{% url 'kreator' %}">Stwórz nową ofertę</a></li>
                    <li><a href="{% url 'pojazdy' %}">Pokaż wszystkie opublikowane oferty</a></li>
                    <li><a href="{% url 'moje_pojazdy' %}">Zobacz swoje oferty</a></li>
                    <li><span>zalogowany jako: {{ request.user.username }}</span></li>
                    <li><a href="{% url 'wyloguj' %}">Wyloguj się</a></li>
                </ul>
            {% else %}
                <ul>
                    <li><a href="{% url 'pojazdy' %}">MotoSell</a></li>
                    <li><a href="{% url 'pojazdy' %}">Pokaż oferty</a></li>
                    <li><a href="{% url 'rejestracja' %}">Zarejestruj się</a></li>
                    <li><a href="{% url 'login' %}">Zaloguj się</a></li>
                </ul>
            {% endif %}
        </div>
        <div class="glowne">
            {% block content %}

            {% endblock %}
        </div>
    </body>
</html>

MotoSellProjekt/MotoSell/templates/MotoSell/edytuj.html
{% extends "MotoSell/base.html" %}
{% block content %}
	<form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Edytuj ofertę</h2>
        {{ formularz_pojazdu }}
        <p>Musisz dodać conajmniej 1 zdjęcie</p>
        {{ formset_galerii }}
        <button type="submit">Zapisz zmiany</button>
    </form>
{% endblock %}

MotoSellProjekt/MotoSell/templates/MotoSell/index.html
{% extends "MotoSell/base.html" %}
{% block content %}
	<p>Jeżeli tu coś widzisz to coś sie zepsuło</p>
{% endblock %}

MotoSellProjekt/MotoSell/templates/MotoSell/kreator.html
{% extends "MotoSell/base.html" %}
{% block content %}
	<form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Formularz kreacji ofert</h2>
        {{ formularz_pojazdu }}
        <p>Musisz dodać conajmniej 1 zdjęcie</p>
        {{ formset_galerii }}
        <br><br><button type="submit">Stwórz ofertę</button>
    </form>
{% endblock %}

MotoSellProjekt/MotoSell/templates/MotoSell/login.html
{% extends "MotoSell/base.html" %}
{% block content %}
	<form method="post">
        {% csrf_token %}
        <h2>Zaloguj się</h2>
        {{ formularz_logowania }}
        <button type="submit">Zaloguj się</button>
    </form>
{% endblock %}

MotoSellProjekt/MotoSell/templates/MotoSell/moje_pojazdy.html
{% extends "MotoSell/base.html" %}
{% block content %}
	<h1>Twoje oferty:</h1>
    {% if not pojazdy_wszystkie  %}
        <h1>Nie ma żadnych pojazdów</h1>
    {% else %}
        {% for pojazd in pojazdy_wszystkie %}
            {% if pojazd.uzytkownik == request.user and not pojazd.czy_usuniety %}
                <div class="oferta">
                    <a href="{% url 'pojazdy' %}/{{ pojazd.id }}">
                        <div class="oferta_napisy">
                            <h3>{{ pojazd.tytul }}</h3>
                            <p>Oferta użytkownika: {{ pojazd.uzytkownik.username }}</p>
                            <p>Marka i model: {{ pojazd.marka }} {{ pojazd.model }}</p>
                            <p>Kategoria: {{ pojazd.kategoria }}</p>
                            {% if pojazd.czy_opublikowany %}
                                <p>Oferta opublikowana</p>
                            {% else %}
                                <p>Oferta nieopublikowana</p>
                            {% endif %}
                        </div>
                        {% for zdjecie in pojazd.zdjecie_set.all %}
                            {% if zdjecie.czy_glowny %}
                                <div class="zdjecie_okladka">
                                    <img src="{{ zdjecie.zdjecie.url }}" alt="Zdjęcie pojazdu">
                                </div>
                            {% endif %}
                        {% endfor %}
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}

MotoSellProjekt/MotoSell/templates/MotoSell/oferta.html
{% extends "MotoSell/base.html" %}
{% block content %}
	<h1>{{ pojazd.tytul }}</h1>
    <p>Opis: {{ pojazd.opis }}</p>
    <p>Oferta użytkownika: {{ pojazd.uzytkownik.username }}</p>
    <p>Kategoria: {{ pojazd.kategoria }}</p>
    <p>Marka: {{ pojazd.marka }}</p>
    <p>Model: {{ pojazd.model }}</p>
    <p>Rok produkcji: {{ pojazd.rok_produkcji }}</p>
    <p>Przebieg: {{ pojazd.przebieg }}</p>
    <p>Pojemność skokowa: {{ pojazd.pojemnosc_skokowa }}</p>
    <p>Rodzaj paliwa: {{ pojazd.rodzaj_paliwa }}</p>
    <p>Zdjęcia pojazdu:</p>
    {% for zdjecie in pojazd.zdjecie_set.all %}
        <img src="{{ zdjecie.zdjecie.url }}" alt="zdjęcie pojazdu" height="200px">
    {% endfor %}
    {% if pojazd.czy_opublikowany %}
        <p>Oferta opublikowana w dniu {{ pojazd.data_publikacji }}</p>
        {% if pojazd.uzytkownik == request.user %}
            <a href="{% url 'cofnij_publikacje' pojazd.id %}"><button>Cofnij publikację</button></a>
        {% endif %}
    {% else %}
        <p>Oferta nieopublikowana</p>
        {% if pojazd.uzytkownik == request.user %}
            <a href="{% url 'publikuj' pojazd.id %}"><button>Publikuj</button></a>
        {% endif %}
    {% endif %}
    {% if pojazd.uzytkownik == request.user %}
        <a href="{% url 'usun' pojazd.id %}"><button>Usuń</button></a>
        <a href="{% url 'edytuj' pojazd.id %}"><button>Edytuj</button></a>
    {% endif %}
{% endblock %}

MotoSellProjekt/MotoSell/templates/MotoSell/pojazdy.html
{% extends "MotoSell/base.html" %}
{% block content %}
    <h1>MotoSell</h1>
    <h3>Oferty Sprzedaży pojazdów drogowych</h3>
	{% if not pojazdy_wszystkie  %}
        <h1>Nie ma żadnych pojazdów</h1>
    {% else %}
        {% for pojazd in pojazdy_wszystkie %}
            {% if pojazd.czy_opublikowany and not pojazd.czy_usuniety %}
                <div class="oferta">
                    <a href="{% url 'pojazdy' %}/{{ pojazd.id }}">
                        <div class="oferta_napisy">
                            <h3>{{ pojazd.tytul }}</h3>
                            <p>Oferta użytkownika: {{ pojazd.uzytkownik.username }}</p>
                            <p>Marka i model: {{ pojazd.marka }} {{ pojazd.model }}</p>
                            <p>Kategoria: {{ pojazd.kategoria }}</p>
                        </div>
                        {% for zdjecie in pojazd.zdjecie_set.all %}
                            {% if zdjecie.czy_glowny %}
                                <div class="zdjecie_okladka">
                                    <img src="{{ zdjecie.zdjecie.url }}" alt="Zdjęcie pojazdu">
                                </div>
                            {% endif %}
                        {% endfor %}
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}

MotoSellProjekt/MotoSell/templates/MotoSell/rejestracja.html
{% extends "MotoSell/base.html" %}
{% block content %}
	<form method="post">
        {% csrf_token %}
        <h2>Zarejestruj się</h2>
        {{ formularz_rejestracji }}
        <button type="submit">Zarejestruj się</button>
    </form>
{% endblock %}